### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by seanjparker**
For issue #23

Added a profile page and refactored the team system

### CODE REVIEW

**Comment by seanjparker** [comment]
Found a bug, if a user creates a team then leaves (or all users leave a team) then the team still exists in the database.

**Comment by kzalys** [comment]
Could you also add another page using pretty much the same template to view a specific user's profile? (GET /user/:id)
It would be accessible to organizers only.

**Comment by seanjparker** [comment]
> Awesome, looks really nice!
> Could you add another field in the personal information card for the team table number?

What is the team table number?

**Comment by kzalys** [comment]
> > Awesome, looks really nice!
> > Could you add another field in the personal information card for the team table number?
> 
> What is the team table number?

As in, the number of the table the team sits at. I want to make it so that when people want to take anything from the hardware library they have to enter their table number so we can easily find them later.

**Comment by seanjparker** [comment]
> Awesome, looks really nice!
> Could you add another field in the personal information card for the team table number?

I have added a new field for each team for them to enter the team number

**Comment by seanjparker** [comment]
> Could you make the team table number field visible (but disabled) even before the user has created a team (some explanation on why it's disabled would be great too)? Because people might get confused on how to set their table number if they haven't created a team.

Good idea, I will add that now

**Pull request merged**
